-- ============================================
-- IN-463 — LLM thematic labels for anchored mood rooms
-- Migration 034
-- ============================================
--
-- Cache table for gpt-4o-mini-generated thematic room names. The
-- anchored mood rooms row on For You ships v1 with literal "If you
-- love {anchor}" labels (Phase 4.5 redirect, migration 033). This
-- migration backs the IN-463 fast-follow: replace those literals with
-- thematic labels generated by an Edge Function on first observation
-- of each anchor.
--
-- Cache shape:
--   - PK: (anchor_tmdb_id, anchor_media_type) — keys on the anchor
--     identity. Same anchor across users → one LLM call → one cached
--     label. Sharable across users.
--   - label TEXT NOT NULL: 2–4 word thematic name (e.g.
--     "Boozy Buddy Comedies"). Forbidden-vocabulary check is enforced
--     at write time inside the Edge Function (mirrors the global
--     mood-rooms cron's FORBIDDEN_WORDS).
--   - description TEXT NULL: optional one-sentence description.
--   - generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(): for staleness
--     audits if we ever invalidate cached labels (e.g. anchor
--     neighbourhood drifts because new titles ship in the catalogue).
--   - openai_model TEXT NOT NULL: which model produced the label.
--     If we move to a newer model later, we can selectively re-issue
--     labels without dumping the whole cache.
--
-- RLS: authenticated SELECT (the client reads labels to render cards).
-- service_role bypasses RLS for writes from the Edge Function.

CREATE TABLE IF NOT EXISTS mood_room_anchor_labels (
  anchor_tmdb_id INTEGER NOT NULL,
  anchor_media_type TEXT NOT NULL CHECK (anchor_media_type IN ('movie', 'tv')),
  label TEXT NOT NULL,
  description TEXT,
  openai_model TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (anchor_tmdb_id, anchor_media_type)
);

ALTER TABLE mood_room_anchor_labels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users read anchor labels"
  ON mood_room_anchor_labels FOR SELECT
  USING (auth.role() = 'authenticated');

COMMENT ON TABLE mood_room_anchor_labels IS
  'Cache of LLM-generated thematic labels for anchored mood rooms (IN-463). '
  'Populated by the label-anchor-room Edge Function on first observation of '
  'each (anchor_tmdb_id, anchor_media_type). Shared across users.';
